apiVersion: v1
kind: Secret
metadata:
  name: mysql-cred
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=  # base64 of 'password'
  MYSQL_DATABASE: ZGI=  # base64 of 'db'
  MYSQL_USER: eXVkaXo=  # base64 of 'yudiz'
  MYSQL_PASSWORD: cGFzc3dvcmQ=  # base64 of 'password'
