apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1 # For easier debugging, set it to one replica. Change to 2 or more for production.
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: wp-config
          configMap:
            name: wp-configmap
            items:
              - key: wp-config.php
                path: wp-config.php
        - name: config-writable
          emptyDir: {}
      initContainers:
        - name: init-config
          image: busybox:latest
          command: ["sh", "-c"]
          args:
            - "cp /config/wp-config.php /config-writable/ && chown www-data:www-data /config-writable/wp-config.php"
          volumeMounts:
            - name: wp-config
              mountPath: /config
            - name: config-writable
              mountPath: /config-writable
      containers:
        - name: wordpress
          image: 851725603941.dkr.ecr.ap-southeast-1.amazonaws.com/ollato:demo
          volumeMounts:
            - name: config-writable
              mountPath: /var/www/html/wp-config.php
              subPath: wp-config.php
          env:
            - name: DB_HOST
              value: mysql-service.default.svc.cluster.local
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-cred
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-cred
                  key: MYSQL_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-cred
                  key: MYSQL_DATABASE
          ports:
            - containerPort: 80
              name: wordpress
---
kind: Service
apiVersion: v1
metadata:
  name: wordpress-service
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30004
